### PR TITLE
Merge Conflicts Fix

### PR DESCRIPTION
**Pull request by cdthomp1**

### CODE REVIEW

**Comment by jadkins89** [comment]
Hey @cdthomp1,

Thanks for your contribution, I should have some time tomorrow to look this over. Stay tuned.

**Comment by jadkins89** [comment]
Hey @cdthomp1,

Sorry to move the goal post on you here but I just refactored the package to now use a more OOP approach which will remove a lot of the duplicate logic that previously existed. Could you refactor this new scrape to conform to this new pattern?

Could you also have the scrape grab the servings and time data as well? It looks like that website is using a wordpress plugin for the recipe similar to the existing scrape for `melskitchencafe.com`. Looking at that scrape may help speed up which selectors to use.

**Comment by cdthomp1** [comment]
@jadkins89 Sure thing, I will work on that for this website. 

Thanks!

**Comment by cdthomp1** [comment]
Closing this PR, will open a new, clean PR with the changes

**Pull request closed without merging**
